--- 
title: "Judul Proposal Penelitian"
author: "Nama Anda"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 
description: ""
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```

# Abstrak
<div style="text-align: justify"> 

Pembaca akan lebih mudah membayangkan apa saja isi dari karya ilmiah. Selain itu, jika abstrak dikemas dengan menarik, maka tentu akan mengundang rasa penasaran untuk membaca lebih lanjut. Abstrak diumpamakan seperti cover book, jika tidak menarik, tentu pembaca akan malas untuk membaca isi keseluruhan dari karya ilmiah tersebut

## Manfaat Abstrak :

1. To the point. Pembaca langsung disuguhkan pada ide pokok yang akan dibahas tanpa perlu membaca isi/pembahasannya. Pembaca dapat menentukan apakah ia akan melanjutkan membaca atau tidak. Ini akan menghemat waktu pembaca
2. Terdapat Keyword (Kata Kunci). Ini sangat penting untuk menekankan kepada pembaca kata yang penting dari karya ilmiah ini. Keyword sifatnya lebih mudah diingat, simpel namun menggambarkan isi dari karya ilmiah, makalah maupun skripsi. Selain itu kata kunci mempermudah penyimpanan secara elektronik.
3. Membantu penulis untuk menentukan pokok/rumusan masalah, teori dan metode penelitian yang digunakan, sumber data, variabel, hasil penelitian, dan simpulan dari penelitian tersebut. Membuat abstrak di awal dapat mencegah penulis untuk out of topic atau keluar dari poko bahasan

Karena tujuannya untuk memudahkan pembaca, maka Penulis harus mampu memberikan gambaran yang jelas dan mudah dimengerti dengan singkat, padat dan jelas

Lalu bagaimana penulisan abstrak yang baik? Berikut penjelasannya

> **Judul Tulisan Abstrak**
Judul adalah kekuatan utama. Buatlah judul dengan menarik, namun tetap sesuai dengan pokok pembahasan. Judul yang menarik akan membuat pembaca penasaran dan lanjut untuk membaca.

> **Latar belakang Tulisan Abstrak**
Ini dari latar belakang adalah MENGAPA kamu mengangkat topik ini. Jelaskan dengan singkat asal mula topik ini dipilih, seperti misalnya berawal dari masalah sosial, lingkungan atau kehidupan sehari-hari. Kamu tidak mungkin mengangkat suatu topik jika tidak ada permasalahan tersebut sebelumnya. Karena inti dari karya tulis adalah menyelesaikan suatu masalah yang ada melalui penelitian ini.

> **Metode Penelitian, Sumber data, Variabel dan pendukung lain**
Cantumkan metode penelitian yang kamu gunakan, sumber data penelitian, variabel serta data pendukung lain sebagai dasar pembuatan karya ilmiah tersebut.

> **Gambaran Tulisan Abstrak**
Jelaskan gambaran dari karya ilmiah kamu dengan singkat, padat namun jelas dan mudah dipahami. Gunakan kata tanya KAPAN, BAGAIMANA, DIMANA dll untuk menjelaskan gambaran tersebut. Kamu bisa menyesuaikannya sesuai dengan pembahasan yang kamu buat.

> **Simpulan Tulisan Abstrak**
Terakhir, Jelaskan simpulan dari hasil penelitian serta solusi untuk mengatasi permasalahan. Intinya, simpulan harus menjawab pertanyaan dan rumusan masalah yang ada secara singkat.

> **Kata Kunci (Keyword)**
Tulis kata kunci yang penting di bawah simpulan. Kamu harus menyertakan minimal 3 kata kunci


# Kata Pengantar

Puji syukur senantiasa kita panjatkan kehadirat Tuhan Yang Maha Esa atas semua limpahan rahmat-Nya sehingga tim dan saya dapat menyelesaikan penyusunan buku yang berjudul **"Metode Penelitian"**, meskipun dengan sangat sederhana. Harapan kami, kirannya buku yang telah tersusun ini dapat bermanfaat menjadi salah satu rujukan maupun pedoman bagi para pembaca, menambah wawasan serta dapat menjadi inspirasi dalam memahami ilmu statistik.  

Sebagai penulis, saya **Bakti Siregar M.Sc** mengakui bahwasanya masih banyak kekurangan yang terkandung di dalamnya. Oleh sebab itu, dengan penuh kerendahan hati saya berharap kepada para pembaca untuk memberikan kritik dan saran demi lebih memperbaiki buku ini.

Tidak lupa, penulis juga mengucapkan terima kasih kepada semua pihak yang telah berjasa memberikan kontribusi dalam rangka menyelesaikan buku ini, yaitu kepada mahasiswa saya di Program Studi Statistika Matana University: 

> 1. Endri Tri Wibowo (alamat email)
> 2. Jihan Selianovira alamat email)
> 3. Kevin Sugianto (alamat email)
> 4. Ardiwan (alamat email)

<br>
**Tentang Penulis:**
<br>
Email      : siregarbakti@gmail.com / siregar.bakti@matanauniversity.ac.id <br>
No.Whatsapp: 081369552544


</div>






